name: Rotate App Registration Secret

on:
  schedule:
    - cron: '0 3 1 */4 *' # At 03:00 on the 1st day every 4th month
  workflow_dispatch:

jobs:
  rotate-secret:
    runs-on: ubuntu-latest

    steps:
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create new App Registration secret
      id: create-secret
      run: |
        NEW_SECRET=$(az ad app credential reset \
          --id ${{ secrets.APP_REGISTRATION_ID }} \
          --append \
          --display-name "RotatedSecret" \
          --years 1 \
          --query password \
          -o tsv)
        echo "::add-mask::$NEW_SECRET"
        echo "secret_value=$NEW_SECRET" >> $GITHUB_OUTPUT

    - name: Update Key Vault secret
      run: |
        az keyvault secret set \
          --vault-name ${{ secrets.KEYVAULT_NAME }} \
          --name ${{ secrets.SECRET_NAME }} \
          --value "${{ steps.create-secret.outputs.secret_value }}"

    - name: Restart Customer App
      run: |
        az webapp restart \
          --name ${{ secrets.CUSTOMER_APP_NAME }} \
          --resource-group ${{ secrets.RESOURCE_GROUP }}

    - name: Restart Admin App
      run: |
        az webapp restart \
          --name ${{ secrets.ADMIN_APP_NAME }} \
          --resource-group ${{ secrets.RESOURCE_GROUP }}
